services:
  nginx:
    image: "nginx:stable-alpine" #alpine - сжатый
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on: # зависит от двух, после поднятия nginx подымуться postgres и php
      - postgres
      - php
  php:
    build:
      context: dockerfiles #папка
      dockerfile: php.Dockerfile #файл откуда взять инстуркцию
    volumes:
      - ./src:/var/www/laravel
  postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    env_file:
      - env/postgres.env
    volumes:
      - pg_data:/var/lib/postgresql/data # чтобы данные от бд сохранялись
  
  composer: # отработает и остановится в интрукции прописано
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      # - db_data:/var/www/laravel
      - ./src:/var/www/laravel
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"] # 
volumes:
  pg_data:

